[database]
dbtype = "postgres"
username = "postgres"
password = "root"
host = "localhost"
port = 5432
db = "venonika"


[server]
domain = "127.0.0.1"
port = 5000


[jwt]
secret = "jaof23r32dlwk"
expiration = 3600


[author]
name = "analog-sombra"
github = "https://github.com/analog_sombra/"
