// Generated by diesel_ext

#![allow(unused)]
#![allow(clippy::all)]


use chrono::NaiveDateTime;
#[derive(Queryable, Debug)]
pub struct User {
    pub id: i32,
    pub user_id: String,
    pub email: Option<String>,
    pub username: Option<String>,
    pub global_name: Option<String>,
    pub avatar: Option<String>,
    pub mfa_enabled: bool,
    pub banner: Option<String>,
    pub verified: bool,
    pub role: /* TODO: unknown type Role */,
    pub status: /* TODO: unknown type Status */,
    pub created_at: Option<NaiveDateTime>,
    pub updated_at: Option<NaiveDateTime>,
}

